	tilepal 0, TEXT, RED, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, TEXT, TEXT, BROWN, BROWN
	tilepal 0, TEXT, TEXT, BROWN, BROWN, BROWN, BROWN, WATER, WATER
	tilepal 0, TEXT, TEXT, BROWN, BROWN, GRAY, TEXT, BROWN, BROWN
	tilepal 0, TEXT, TEXT, TEXT, YELLOW, YELLOW, YELLOW, TEXT, RED
	tilepal 0, TEXT, TEXT, BROWN, BROWN, GREEN, GREEN, TEXT, TEXT
	tilepal 0, TEXT, TEXT, TEXT, TEXT, WATER, WATER, TEXT, RED
	tilepal 0, TEXT, TEXT, BROWN, WATER, GREEN, GREEN, TEXT, TEXT
	tilepal 0, BROWN, BROWN, BROWN, TEXT, TEXT, GRAY, GRAY, TEXT
	tilepal 0, TEXT, TEXT, GRAY, GRAY, BROWN, BROWN, BROWN, TEXT
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, YELLOW
	tilepal 0, YELLOW, YELLOW, GRAY, GRAY, WATER, WATER, WATER, WATER

rept 16
	db $ff
endr

	tilepal 1, GRAY, GRAY, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, GRAY, GRAY
