	tilepal 0, YELLOW, TEXT, TEXT, TEXT, WATER, YELLOW, TEXT, TEXT
	tilepal 0, GRAY, GRAY, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 0, TEXT, TEXT, TEXT, TEXT, WATER, TEXT, RED, TEXT
	tilepal 0, RED, RED, TEXT, TEXT, TEXT, TEXT, BROWN, GRAY
	tilepal 0, GRAY, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, RED
	tilepal 0, RED, RED, TEXT, GRAY, BROWN, GRAY, BROWN, BROWN
	tilepal 0, GRAY, RED, TEXT, TEXT, TEXT, TEXT, TEXT, YELLOW
	tilepal 0, YELLOW, YELLOW, BROWN, BROWN, BROWN, BROWN, BROWN, WATER
	tilepal 0, RED, TEXT, GRAY, TEXT, TEXT, TEXT, RED, RED
	tilepal 0, TEXT, TEXT, TEXT, BROWN, GRAY, GRAY, BROWN, BROWN
	tilepal 0, RED, GRAY, TEXT, TEXT, TEXT, TEXT, RED, RED
	tilepal 0, TEXT, TEXT, TEXT, BROWN, WATER, GRAY, GREEN, BROWN

rept 16
	db $ff
endr

	tilepal 1, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, GRAY
	tilepal 1, GRAY, GRAY, GRAY, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BROWN, YELLOW, YELLOW
	tilepal 1, YELLOW, TEXT
